{
  "swagger" : "2.0",
  "info" : {
    "description" : "The HTTP API for Event Store",
    "version" : "4.0.2",
    "title" : "Event Store HTTP API",
    "contact" : {
      "email" : "you@your-company.com"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host" : "virtserver.swaggerhub.com",
  "basePath" : "/ChrisChinchilla/EventStore/1.0.0",
  "schemes" : [ "https" ],
  "paths" : {
    "/streams/{stream}" : {
      "get" : {
        "summary" : "Reads a stream",
        "description" : "Read a stream, receiving a standard AtomFeed document as a response.",
        "operationId" : "readStream",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream ID",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "embed",
          "in" : "query",
          "required" : false,
          "type" : "string",
          "enum" : [ "None", "Content", "Rich", "Body", "PrettyBody", "TryHarder" ]
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "404" : {
            "description" : "Not found"
          }
        }
      },
      "post" : {
        "summary" : "Create a stream",
        "description" : "Create a new stream.",
        "operationId" : "createStream",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The name of the new stream",
          "required" : true,
          "type" : "string"
        }, {
          "in" : "body",
          "name" : "streamItem",
          "description" : "Stream to create",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/StreamItem"
          }
        } ],
        "responses" : {
          "201" : {
            "description" : "New stream created"
          },
          "400" : {
            "description" : "Bad request"
          }
        }
      },
      "delete" : {
        "summary" : "Deletes a stream",
        "description" : "",
        "operationId" : "deleteStream",
        "produces" : [ "application/xml", "application/json" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream ID to delete",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "204" : {
            "description" : "Stream deleted"
          }
        }
      }
    },
    "/streams/{stream}/incoming/{guid}" : {
      "post" : {
        "summary" : "An alternative URL to post events to",
        "description" : "A URL generated by Event Store if you don't supply an ID when creating a stream. You then use this URL to post events to.",
        "operationId" : "incomingUrl",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The name of the stream",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "guid",
          "in" : "path",
          "description" : "Autogenerated UUID",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "New event created"
          },
          "400" : {
            "description" : "Bad request"
          }
        }
      }
    },
    "/streams/{stream}/{event}" : {
      "get" : {
        "summary" : "Read a stream event",
        "description" : "Reads a single event from a stream.",
        "operationId" : "readSingleStreamEvent",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream ID",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "event",
          "in" : "path",
          "description" : "The event ID",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "embed",
          "in" : "query",
          "required" : false,
          "type" : "string",
          "enum" : [ "None", "Content", "Rich", "Body", "PrettyBody", "TryHarder" ]
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "404" : {
            "description" : "Not found"
          }
        }
      }
    },
    "/streams/{stream}/{event}/{count}" : {
      "get" : {
        "summary" : "Paginate backwards through stream events",
        "description" : "Paginate backwards though stream events by a specified amount.",
        "operationId" : "getSpecifiedStreamEvents",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream ID",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "event",
          "in" : "path",
          "description" : "The event ID",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "count",
          "in" : "path",
          "description" : "How many events to skip backwards from in the request.",
          "required" : true,
          "type" : "integer",
          "format" : "int64"
        }, {
          "name" : "embed",
          "in" : "query",
          "required" : false,
          "type" : "string",
          "enum" : [ "None", "Content", "Rich", "Body", "PrettyBody", "TryHarder" ]
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "404" : {
            "description" : "Not found"
          }
        }
      }
    },
    "/streams/{stream}/{event}/backward/{count}" : {
      "get" : {
        "summary" : "Paginate backwards through stream events",
        "description" : "Paginate backwards though stream events by a specified amount.",
        "operationId" : "pageBackwardsStreamEvents",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream ID",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "event",
          "in" : "path",
          "description" : "The event ID",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "count",
          "in" : "path",
          "description" : "How many events to skip backwards from in the request.",
          "required" : true,
          "type" : "integer",
          "format" : "int64"
        }, {
          "name" : "embed",
          "in" : "query",
          "required" : false,
          "type" : "string",
          "enum" : [ "None", "Content", "Rich", "Body", "PrettyBody", "TryHarder" ]
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "404" : {
            "description" : "Not found"
          }
        }
      }
    },
    "/streams/{stream}/{event}/forward/{count}" : {
      "get" : {
        "summary" : "Paginate forwards through stream events",
        "description" : "Paginate forwards though stream events by a specified amount.",
        "operationId" : "pageForwardsStreamEvents",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream ID",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "event",
          "in" : "path",
          "description" : "The event ID",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "count",
          "in" : "path",
          "description" : "How many events to skip forwards in the request.",
          "required" : true,
          "type" : "integer",
          "format" : "int64"
        }, {
          "name" : "embed",
          "in" : "query",
          "required" : false,
          "type" : "string",
          "enum" : [ "None", "Content", "Rich", "Body", "PrettyBody", "TryHarder" ]
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "404" : {
            "description" : "Not found"
          }
        }
      }
    },
    "/streams/{stream}/metadata" : {
      "get" : {
        "summary" : "Reads the metadata of a stream",
        "description" : "Returns metadata of a stream, typically information associated with an event that is not part of the event.",
        "operationId" : "readStreamMetadata",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream ID",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "embed",
          "in" : "query",
          "required" : false,
          "type" : "string",
          "enum" : [ "None", "Content", "Rich", "Body", "PrettyBody", "TryHarder" ]
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          }
        }
      },
      "post" : {
        "summary" : "Update stream metadata",
        "description" : "Update the metadata of a stream.",
        "operationId" : "updateStreamMetadata",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The name of the stream",
          "required" : true,
          "type" : "string"
        }, {
          "in" : "body",
          "name" : "streamMetadataItem",
          "description" : "Metadata object",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/StreamMetadataItem"
          }
        } ],
        "responses" : {
          "201" : {
            "description" : "New stream created"
          },
          "400" : {
            "description" : "Bad request"
          }
        }
      }
    },
    "/streams/$all" : {
      "get" : {
        "summary" : "Returns all events from all streams",
        "description" : "Returns all events from all streams, you must provide user details.",
        "operationId" : "readAll",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "embed",
          "in" : "query",
          "required" : false,
          "type" : "string",
          "enum" : [ "None", "Content", "Rich", "Body", "PrettyBody", "TryHarder" ]
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "404" : {
            "description" : "Not found"
          }
        }
      }
    },
    "/subscriptions" : {
      "get" : {
        "summary" : "Get information for all subscriptions",
        "description" : "Needed",
        "operationId" : "readSubscriptions",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "New persistant subscription"
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      }
    },
    "/subscriptions/{stream}" : {
      "get" : {
        "summary" : "Returns stream information",
        "description" : "Needed",
        "operationId" : "streamInformation",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream name",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "New persistant subscription"
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      }
    },
    "/subscriptions/{stream}/{subscription}/info" : {
      "get" : {
        "summary" : "Reads stream information via a persistent subscription",
        "description" : "Needed",
        "operationId" : "readSubscriptionInformation",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream the persistent subscription is on",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "subscription",
          "in" : "path",
          "description" : "The name of the subscription group",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "New persistant subscription"
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      }
    },
    "/subscriptions/{stream}/{subscription}" : {
      "get" : {
        "summary" : "Reads a stream via a persistent subscription",
        "description" : "By default, reading a stream via a persistent subscription will return a single event per request and will not embed the event properties as part of the response. Read [Reading Streams]({{site.baseurl}}/http-api/reading-streams) for information on the different embed levels.",
        "operationId" : "readSubscription",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream the persistent subscription is on",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "subscription",
          "in" : "path",
          "description" : "The name of the subscription group",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "embed",
          "in" : "query",
          "description" : "Needed",
          "required" : false,
          "type" : "string",
          "enum" : [ "None", "Content", "Rich", "Body", "PrettyBody", "TryHarder" ]
        } ],
        "responses" : {
          "200" : {
            "description" : "New persistant subscription"
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      },
      "post" : {
        "summary" : "Update a persistant subscription",
        "description" : "You can edit the settings of an existing subscription while it is running. This will drop the current subscribers and will reset the subscription internally.",
        "operationId" : "updateSubscription",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream the persistent subscription is on",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "subscription",
          "in" : "path",
          "description" : "The name of the subscription group",
          "required" : true,
          "type" : "string"
        }, {
          "in" : "body",
          "name" : "subscriptionItem",
          "description" : "Subscription to create",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/SubscriptionItem"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "New persistant subscription"
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      },
      "put" : {
        "summary" : "Create a persistant subscription",
        "description" : "Before interacting with a subscription group, you need to create one. You will receive an error if you attempt to create a subscription group more than once. This requires [admin permissions](/server/access-control-lists).",
        "operationId" : "createSubscription",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream the persistent subscription is on",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "subscription",
          "in" : "path",
          "description" : "The name of the subscription group",
          "required" : true,
          "type" : "string"
        }, {
          "in" : "body",
          "name" : "subscriptionItem",
          "description" : "Subscription to create",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/SubscriptionItem"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "New persistant subscription"
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      },
      "delete" : {
        "summary" : "Deletes a subscription",
        "description" : "",
        "operationId" : "deleteSubscription",
        "produces" : [ "application/xml", "application/json" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream the persistent subscription is on",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "subscription",
          "in" : "path",
          "description" : "The name of the subscription group",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "New persistant subscription"
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      }
    },
    "/subscriptions/{stream}/{subscription}/{count}" : {
      "get" : {
        "summary" : "Reads a stream via a persistent subscription and return a specific number of events",
        "description" : "By default, reading a stream via a persistent subscription will return a single event per request and will not embed the event properties as part of the response. Read [Reading Streams]({{site.baseurl}}/http-api/reading-streams) for information on the different embed levels.",
        "operationId" : "readSubscriptionWithCount",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream the persistent subscription is on",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "subscription",
          "in" : "path",
          "description" : "The name of the subscription group",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "count",
          "in" : "path",
          "description" : "How many events to return for the request.",
          "required" : true,
          "type" : "integer",
          "format" : "int64"
        }, {
          "name" : "embed",
          "in" : "query",
          "required" : false,
          "type" : "string",
          "enum" : [ "None", "Content", "Rich", "Body", "PrettyBody", "TryHarder" ]
        } ],
        "responses" : {
          "200" : {
            "description" : "New persistant subscription"
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      }
    },
    "/subscriptions/{stream}/{subscription}/ack/{messageid}" : {
      "post" : {
        "summary" : "Acknowledge a single message",
        "description" : "Clients must acknowledge (or not acknowledge) messages in the competing consumer model. If the client fails to respond in the given timeout period, the message will be retried. You should use the `rel` links in the feed for acknowledgements not bookmark URIs as they are subject to change in future versions.",
        "operationId" : "acknowledgeSingleMessage",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream the persistent subscription is on",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "subscription",
          "in" : "path",
          "description" : "The name of the subscription group",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "messageid",
          "in" : "path",
          "description" : "The id of the message that needs to be acked",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "New persistant subscription"
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      }
    },
    "/subscriptions/{stream}/{subscription}/ack" : {
      "post" : {
        "summary" : "Acknowledge multiple messages",
        "description" : "Clients must acknowledge (or not acknowledge) messages in the competing consumer model. If the client fails to respond in the given timeout period, the message will be retried. You should use the `rel` links in the feed for acknowledgements not bookmark URIs as they are subject to change in future versions.",
        "operationId" : "acknowledgeMultipleMessages",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream the persistent subscription is on",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "subscription",
          "in" : "path",
          "description" : "The name of the subscription group",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "ids",
          "in" : "query",
          "description" : "The ids of the messages that need to be acked separated by commas",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "New persistant subscription"
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      }
    },
    "/subscriptions/{stream}/{subscription}/nack/{messageid}" : {
      "post" : {
        "summary" : "Negative acknowledge a single message",
        "description" : "Clients must acknowledge (or not acknowledge) messages in the competing consumer model. If the client fails to respond in the given timeout period, the message will be retried. You should use the `rel` links in the feed for acknowledgements not bookmark URIs as they are subject to change in future versions.",
        "operationId" : "negativeAcknowledgeSingleMessage",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream the persistent subscription is on",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "subscription",
          "in" : "path",
          "description" : "The name of the subscription group",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "messageid",
          "in" : "path",
          "description" : "The id of the message that needs to be nacked",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "action",
          "in" : "query",
          "description" : "<ul><li>**Park** - Don't retry the message, park it until a request is sent to reply the parked messages<li>**Retry** - Retry the message<li>**Skip** - Discard the message<li>**Stop** - Stop the subscription</ul>",
          "required" : false,
          "type" : "string",
          "enum" : [ "Park", "Retyr", "Skip", "Stop" ]
        } ],
        "responses" : {
          "200" : {
            "description" : "New persistant subscription"
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      }
    },
    "/subscriptions/{stream}/{subscription}/nack" : {
      "post" : {
        "summary" : "Negative acknowledge multiple messages",
        "description" : "Clients must acknowledge (or not acknowledge) messages in the competing consumer model. If the client fails to respond in the given timeout period, the message will be retried. You should use the `rel` links in the feed for acknowledgements not bookmark URIs as they are subject to change in future versions.",
        "operationId" : "negativeAcknowledgeMultipleMessages",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream the persistent subscription is on",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "subscription",
          "in" : "path",
          "description" : "The name of the subscription group",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "ids",
          "in" : "query",
          "description" : "The ids of the messages that need to be nacked separated by commas",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "action",
          "in" : "query",
          "description" : "<ul><li>**Park** - Don't retry the message, park it until a request is sent to reply the parked messages<li>**Retry** - Retry the message<li>**Skip** - Discard the message<li>**Stop** - Stop the subscription</ul>",
          "required" : false,
          "type" : "string",
          "enum" : [ "Park", "Retry", "Skip", "Stop" ]
        } ],
        "responses" : {
          "200" : {
            "description" : "New persistant subscription"
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      }
    },
    "/subscriptions/{stream}/{subscription}/replayParked" : {
      "post" : {
        "summary" : "Replay any previously parked messages in a stream",
        "description" : "Replay any previously parked messages in a stream that were parked by a negative acknowledgement action.",
        "operationId" : "replayParkedMessages",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "stream",
          "in" : "path",
          "description" : "The stream the persistent subscription is on",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "subscription",
          "in" : "path",
          "description" : "The name of the subscription group",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "New persistant subscription"
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      }
    }
  },
  "definitions" : {
    "StreamItem" : {
      "type" : "object",
      "properties" : {
        "ResolveLinkTos" : {
          "type" : "boolean",
          "description" : "Whether to resolve link events"
        },
        "startFrom" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "Which event position in the stream the subscription should start from"
        },
        "extraStatistics" : {
          "type" : "boolean",
          "description" : "Whether to track latency statistics on this subscription"
        },
        "checkPointAfterMilliseconds" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The amount of time to try to checkpoint after"
        },
        "liveBufferSize" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The size of the buffer (in-memory) listening to live messages as they happen before paging occurs"
        },
        "readBatchSize" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The number of events to read per batch when reading the history"
        },
        "bufferSize" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The number of events to cache when paging through history"
        },
        "maxCheckPointCount" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The maximum number of messages not checkpointed before forcing a checkpoint"
        },
        "maxRetryCount" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The maximum number of retries (due to timeout) before a message is considered to be parked"
        },
        "maxSubscriberCount" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The maximum number of subscribers allowed"
        },
        "messageTimeoutMilliseconds" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The amount of time after which to consider a message as timedout and retried"
        },
        "minCheckPointCount" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The minimum number of messages to write to a checkpoint"
        },
        "namedConsumerStrategy" : {
          "type" : "string",
          "description" : "The strategy to use for distributing events to client consumers",
          "enum" : [ "RoundRobin", "DispatchToSingle", "Pinned" ]
        }
      },
      "example" : {
        "minCheckPointCount" : 2,
        "startFrom" : 0,
        "ResolveLinkTos" : true,
        "readBatchSize" : 5,
        "namedConsumerStrategy" : "RoundRobin",
        "extraStatistics" : true,
        "maxRetryCount" : 7,
        "liveBufferSize" : 1,
        "messageTimeoutMilliseconds" : 3,
        "maxCheckPointCount" : 2,
        "maxSubscriberCount" : 9,
        "checkPointAfterMilliseconds" : 6,
        "bufferSize" : 5
      }
    },
    "StreamMetadataItem" : {
      "type" : "object",
      "properties" : {
        "eventId" : {
          "type" : "string",
          "description" : "Alphanumeric ID"
        },
        "eventType" : {
          "type" : "string",
          "description" : "The type of event"
        },
        "data" : {
          "$ref" : "#/definitions/StreamMetadataItem_data"
        }
      },
      "example" : {
        "eventId" : "eventId",
        "data" : {
          "readRole" : "readRole",
          "metaReadRole" : "metaReadRole"
        },
        "eventType" : "eventType"
      }
    },
    "SubscriptionItem" : {
      "type" : "object",
      "properties" : {
        "ResolveLinkTos" : {
          "type" : "boolean",
          "description" : "Whether to resolve link events"
        },
        "startFrom" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "Which event position in the stream the subscription should start from"
        },
        "extraStatistics" : {
          "type" : "boolean",
          "description" : "Whether to track latency statistics on this subscription"
        },
        "checkPointAfterMilliseconds" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The amount of time to try to checkpoint after"
        },
        "liveBufferSize" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The size of the buffer (in-memory) listening to live messages as they happen before paging occurs"
        },
        "readBatchSize" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The number of events to read per batch when reading the history"
        },
        "bufferSize" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The number of events to cache when paging through history"
        },
        "maxCheckPointCount" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The maximum number of messages not checkpointed before forcing a checkpoint"
        },
        "maxRetryCount" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The maximum number of retries (due to timeout) before a message is considered to be parked"
        },
        "maxSubscriberCount" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The maximum number of subscribers allowed"
        },
        "messageTimeoutMilliseconds" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The amount of time after which to consider a message as timedout and retried"
        },
        "minCheckPointCount" : {
          "type" : "integer",
          "format" : "int64",
          "description" : "The minimum number of messages to write to a checkpoint"
        },
        "namedConsumerStrategy" : {
          "type" : "string",
          "description" : "The strategy to use for distributing events to client consumers",
          "enum" : [ "RoundRobin", "DispatchToSingle", "Pinned" ]
        }
      },
      "example" : {
        "minCheckPointCount" : 2,
        "startFrom" : 0,
        "ResolveLinkTos" : true,
        "readBatchSize" : 5,
        "namedConsumerStrategy" : "RoundRobin",
        "extraStatistics" : true,
        "maxRetryCount" : 7,
        "liveBufferSize" : 1,
        "messageTimeoutMilliseconds" : 3,
        "maxCheckPointCount" : 2,
        "maxSubscriberCount" : 9,
        "checkPointAfterMilliseconds" : 6,
        "bufferSize" : 5
      }
    },
    "StreamMetadataItem_data" : {
      "properties" : {
        "readRole" : {
          "type" : "string",
          "description" : "The roles allowed to read the stream."
        },
        "metaReadRole" : {
          "type" : "string",
          "description" : "The roles allowed to read the stream metadata."
        }
      },
      "example" : {
        "readRole" : "readRole",
        "metaReadRole" : "metaReadRole"
      }
    }
  }
}
